server:
  port: 8082
spring:
  application:
    name: demo2
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 6198c6c9-9771-42eb-a131-8da22b227162
        username: nacos
        password: nacos
#      config:
#        server-addr: 127.0.0.1:8848
#        namespace: 6198c6c9-9771-42eb-a131-8da22b227162
#
#
#  config:
#    import:
#     - optional:nacos:demo1.yml